# Generated by Django 3.2.9 on 2021-11-22 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('maximum_collaborators', models.IntegerField(default=0, null=True)),
                ('collaborators', models.IntegerField(default=0, null=True)),
                ('created_user_id', models.IntegerField(null=True)),
                ('project_status', models.CharField(default='In progress', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollaborationOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
