# Generated by Django 3.2.9 on 2021-11-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='collaborators_ids',
            field=models.CharField(default='[]', max_length=255, null=True),
        ),
    ]
